# Generated by Django 5.2.6 on 2025-10-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmark",
            name="cpa",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
