# Generated by Django 5.2.6 on 2025-09-28 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to="reports.profile",
            ),
        ),
    ]
