# Generated by Django 5.2.6 on 2025-10-05 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0007_alter_studentmark_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_courses", to="reports.studentprofile"
            ),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="grade",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reports.studentprofile"
            ),
        ),
    ]
