# Generated by Django 5.2.6 on 2025-10-05 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0008_alter_course_students_alter_studentmark_grade_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="course",
            name="lecturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="reports.studentprofile"
            ),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="gpa",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="grade",
            field=models.CharField(default=0.0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="studentmark",
            unique_together={("student", "course")},
        ),
    ]
