# Generated by Django 5.2.6 on 2025-10-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0010_alter_course_lecturer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="registration_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
