# Generated by Django 5.2.6 on 2025-10-06 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0011_alter_studentprofile_registration_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentmark",
            name="gpa",
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="grade",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="reports.profile"
            ),
        ),
        migrations.CreateModel(
            name="LecturerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.profile",
                    ),
                ),
            ],
        ),
    ]
