# Generated by Django 5.2.6 on 2025-10-06 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0012_remove_studentmark_gpa_alter_studentmark_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturerprofile",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lecturerprofile",
            name="office_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="lecturerprofile",
            name="specialization",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="lecturerprofile",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lecturer_profile",
                to="reports.profile",
            ),
        ),
    ]
