# Generated by Django 5.2.6 on 2025-10-06 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0013_lecturerprofile_department_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentmark",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="studentmark",
            name="gpa",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentmark",
            name="lecturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="given_marks",
                to="reports.profile",
            ),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="score",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marks",
                to="reports.profile",
            ),
        ),
    ]
