# Generated by Django 5.2.6 on 2025-10-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0014_alter_studentmark_unique_together_studentmark_gpa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("lecturer", "Lecturer"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
