# Generated by Django 5.2.6 on 2025-10-06 11:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0015_profile_name_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmark",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="credit_units",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="lecturer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses_taught",
                to="reports.profile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="courses_enrolled", to="reports.profile"
            ),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="gpa",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="grade",
            field=models.CharField(default="F", max_length=2),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="lecturer",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lecturer_marks",
                to="reports.profile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_marks",
                to="reports.profile",
            ),
        ),
    ]
