# Generated by Django 5.2.6 on 2025-10-06 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0016_studentmark_created_at_alter_course_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentmark",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="gpa",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="grade",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="lecturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="given_marks",
                to="reports.profile",
            ),
        ),
        migrations.AlterField(
            model_name="studentmark",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marks",
                to="reports.profile",
            ),
        ),
    ]
